const API='';
const $=id=>document.getElementById(id);
let uuid=localStorage.getItem('who-is-ai.uuid');if(!uuid){uuid=crypto.randomUUID();localStorage.setItem('who-is-ai.uuid',uuid)}
$('nickname').value=localStorage.getItem('who-is-ai.name')||'';
{ const savedLang=localStorage.getItem('who-is-ai.lang'); const browserLang=(navigator.language||'en').split('-')[0]; $('language').value=savedLang||(['en','zh','de','fr','es','ja'].includes(browserLang)?browserLang:'en'); }
let player=null, world={strangers:[]}, nearest=null, conversation=null, es=null;
async function post(path,data){const r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw Error(j.error||r.status);return j}
async function get(path){const r=await fetch(API+path);const j=await r.json();if(!r.ok)throw Error(j.error||r.status);return j}
function toast(s){$('toast').textContent=s;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2500)}
$('enter').onclick=async()=>{try{const displayName=($('nickname').value.trim()||`Guest-${uuid.slice(0,4)}`).slice(0,24),language=$('language').value;localStorage.setItem('who-is-ai.name',displayName);localStorage.setItem('who-is-ai.lang',language);const d=await post('/api/session',{uuid,displayName,language});player=d.player;$('score').textContent=player.score;$('landing').classList.add('hidden');$('game').classList.remove('hidden');$('ambient').volume=.16;$('ambient').play().catch(()=>{});startWorld();}catch(e){$('landingError').textContent=e.message}};
$('rankBtn').onclick=showLeaderboard;

function connectEvents(){es=new EventSource(`/api/events?uuid=${encodeURIComponent(uuid)}`);es.onmessage=e=>{const d=JSON.parse(e.data);if(d.type==='world')world=d;if(d.type==='incoming_conversation'){conversation=d.conversation;renderConversation()}if(d.type==='conversation_update'&&conversation?.id===d.conversation.id){conversation=d.conversation;renderConversation()}if(d.type==='conversation_revealed'&&conversation?.id===d.conversation.id){conversation=d.conversation;renderConversation()}if(d.type==='conversation_ended'&&conversation?.id===d.conversationId){conversation=null;renderConversation()}}}

// --- minimal WebGL 3D renderer ---
let gl,prog,bufPos,bufNorm,bufCol,loc={},keys={},pos={x:0,z:5,yaw:0},last=performance.now(),lastNet=0;
const objects=[];
function M4(){return new Float32Array(16)}function ident(){let m=M4();m[0]=m[5]=m[10]=m[15]=1;return m}
function mul(a,b){let o=M4();for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}
function perspective(fov,asp,n,f){let t=1/Math.tan(fov/2),m=M4();m[0]=t/asp;m[5]=t;m[10]=(f+n)/(n-f);m[11]=-1;m[14]=2*f*n/(n-f);return m}
function lookAt(ex,ey,ez,cx,cy,cz){let zx=ex-cx,zy=ey-cy,zz=ez-cz;let l=Math.hypot(zx,zy,zz);zx/=l;zy/=l;zz/=l;let xx=zz,xy=0,xz=-zx;l=Math.hypot(xx,xz);xx/=l;xz/=l;let yx=zy*xz,yy=zz*xx-zx*xz,yz=-zy*xx;return new Float32Array([xx,yx,zx,0,xy,yy,zy,0,xz,yz,zz,0,-(xx*ex+xz*ez),-(yx*ex+yy*ey+yz*ez),-(zx*ex+zy*ey+zz*ez),1])}
function model(x,y,z,sx,sy,sz,ry=0){let c=Math.cos(ry),s=Math.sin(ry);return new Float32Array([c*sx,0,-s*sx,0,0,sy,0,0,s*sz,0,c*sz,0,x,y,z,1])}
const V=`attribute vec3 p;attribute vec3 n;uniform mat4 mvp;uniform mat4 model;varying float light;void main(){vec3 N=normalize((model*vec4(n,0.0)).xyz);light=.34+.66*max(dot(N,normalize(vec3(.35,.8,.45))),0.0);gl_Position=mvp*vec4(p,1.0);}`;
const F=`precision mediump float;uniform vec3 color;varying float light;void main(){gl_FragColor=vec4(color*light,1.0);}`;
const cubeP=[-1,-1,-1, 1,-1,-1,1,1,-1,-1,-1,-1,1,1,-1,-1,1,-1,  -1,-1,1,-1,1,1,1,1,1,-1,-1,1,1,1,1,1,-1,1, -1,1,-1,1,1,-1,1,1,1,-1,1,-1,1,1,1,-1,1,1, -1,-1,-1,-1,-1,1,1,-1,1,-1,-1,-1,1,-1,1,1,-1,-1, 1,-1,-1,1,-1,1,1,1,1,1,-1,-1,1,1,1,1,1,-1, -1,-1,-1,-1,1,-1,-1,1,1,-1,-1,-1,-1,1,1,-1,-1,1];
const cubeN=[];[[0,0,-1],[0,0,1],[0,1,0],[0,-1,0],[1,0,0],[-1,0,0]].forEach(n=>{for(let i=0;i<6;i++)cubeN.push(...n)});
function shader(type,src){let s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
function add(x,y,z,sx,sy,sz,color,ry=0){objects.push({x,y,z,sx,sy,sz,color,ry})}
function buildScene(){objects.length=0;add(0,-.15,0,31,.12,31,[.11,.16,.22]);for(let i=-25;i<=25;i+=10){add(i,.03,0,.025,.02,30,[.12,.25,.30]);add(0,.03,i,30,.02,.025,[.12,.25,.30])}[[0,0],[15,-9],[-18,-12],[4,19]].forEach((p,i)=>add(p[0],i?1.6:.5,p[1],i===0?2.5:2.6,i===0?.5:1.6,i===0?2.5:2.6,i===0?[.28,.46,.55]:[.18,.29,.40]));[[-29,-29],[29,-29],[-29,29],[29,29]].forEach((p,i)=>add(p[0],3,p[1],4.5,3,4.5,i%2?[.07,.15,.25]:[.09,.19,.29]));[[-8,-5],[8,5],[-18,12],[18,-13],[-23,-7],[22,15],[7,-20],[-6,21]].forEach(p=>{add(p[0],1,p[1],.2,1,.2,[.25,.16,.09]);add(p[0],2.7,p[1],1,1,1,[.08,.29,.22])});[[-6,0],[6,0],[0,-7],[0,7],[-17,-17],[17,17],[-17,17],[17,-17]].forEach(p=>{add(p[0],1.6,p[1],.08,1.6,.08,[.28,.36,.44]);add(p[0],3.35,p[1],.22,.22,.22,[.45,.95,.83])})}
function startWorld(){connectEvents();const c=$('gl');gl=c.getContext('webgl',{antialias:true});if(!gl){toast('WebGL unavailable');return}let vs=shader(gl.VERTEX_SHADER,V),fs=shader(gl.FRAGMENT_SHADER,F);prog=gl.createProgram();gl.attachShader(prog,vs);gl.attachShader(prog,fs);gl.linkProgram(prog);gl.useProgram(prog);bufPos=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,bufPos);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(cubeP),gl.STATIC_DRAW);let ap=gl.getAttribLocation(prog,'p');gl.enableVertexAttribArray(ap);gl.vertexAttribPointer(ap,3,gl.FLOAT,false,0,0);bufNorm=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,bufNorm);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(cubeN),gl.STATIC_DRAW);let an=gl.getAttribLocation(prog,'n');gl.enableVertexAttribArray(an);gl.vertexAttribPointer(an,3,gl.FLOAT,false,0,0);loc.mvp=gl.getUniformLocation(prog,'mvp');loc.model=gl.getUniformLocation(prog,'model');loc.color=gl.getUniformLocation(prog,'color');gl.enable(gl.DEPTH_TEST);buildScene();window.addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyE'&&!e.repeat&&!conversation&&nearest)beginTalk(nearest);if(e.code==='Escape'&&conversation?.revealed){conversation=null;renderConversation()}});window.addEventListener('keyup',e=>keys[e.code]=false);requestAnimationFrame(frame)}
function drawObj(o,vp){let md=model(o.x,o.y,o.z,o.sx,o.sy,o.sz,o.ry||0),mvp=mul(vp,md);gl.uniformMatrix4fv(loc.model,false,md);gl.uniformMatrix4fv(loc.mvp,false,mvp);gl.uniform3fv(loc.color,o.color);gl.drawArrays(gl.TRIANGLES,0,36)}
function frame(now){let dt=Math.min(.05,(now-last)/1000);last=now;if(!conversation){let dx=(keys.KeyD?1:0)-(keys.KeyA?1:0),dz=(keys.KeyS?1:0)-(keys.KeyW?1:0);if(dx||dz){let l=Math.hypot(dx,dz);dx/=l;dz/=l;let s=(keys.ShiftLeft||keys.ShiftRight)?7:4;pos.x=Math.max(-29,Math.min(29,pos.x+dx*s*dt));pos.z=Math.max(-29,Math.min(29,pos.z+dz*s*dt));pos.yaw=Math.atan2(dx,dz)}}if(now-lastNet>300){lastNet=now;post('/api/position',{uuid,x:pos.x,z:pos.z,rotation:pos.yaw}).catch(()=>{})}resize();gl.viewport(0,0,gl.canvas.width,gl.canvas.height);gl.clearColor(.025,.05,.09,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);let cam=[pos.x,5,pos.z+8],view=lookAt(...cam,pos.x,1,pos.z),proj=perspective(Math.PI/3,gl.canvas.width/gl.canvas.height,.1,120),vp=mul(proj,view);for(const o of objects)drawObj(o,vp);nearest=null;let best=999;for(const s of world.strangers||[]){let d=Math.hypot(s.x-pos.x,s.z-pos.z);if(d<best){best=d;nearest=s}drawObj({x:s.x,y:1,z:s.z,sx:.32,sy:1,sz:.32,color:d<4.2?[.95,.75,.35]:[.65,.77,.95],ry:s.rotation||0},vp);drawObj({x:s.x,y:2.05,z:s.z,sx:.27,sy:.27,sz:.27,color:[.92,.70,.55]},vp)}drawObj({x:pos.x,y:1,z:pos.z,sx:.34,sy:1.05,sz:.34,color:[.25,.90,.78],ry:pos.yaw},vp);$('talkPrompt').classList.toggle('hidden',!(nearest&&best<4.2&&!conversation));if(nearest&&best<4.2)$('nearName').textContent=nearest.displayName;requestAnimationFrame(frame)}
function resize(){let c=gl.canvas,dpr=Math.min(devicePixelRatio,2),w=Math.floor(c.clientWidth*dpr),h=Math.floor(c.clientHeight*dpr);if(c.width!==w||c.height!==h){c.width=w;c.height=h}}

async function beginTalk(t){try{const d=await post('/api/conversation/start',{uuid,targetId:t.id});conversation=d.conversation;renderConversation()}catch(e){toast(e.message)}}
function renderConversation(){const el=$('conversation');if(!conversation){el.classList.add('hidden');el.innerHTML='';return}el.classList.remove('hidden');const c=conversation;const isFreeChat=Boolean(c.alreadyJudged);const roundsLocked=!isFreeChat&&c.roundsUsed>=5;let messages=(c.messages||[]).map((m,i)=>{let mine=m.senderId!==c.other.id;return `<div class="bubble ${mine?'me':'them'}"><div data-display="${i}">${esc(m.displayText||m.originalText)}</div>${!mine&&m.translatedText&&m.translatedText!==m.originalText?`<button data-original="${i}">Show original · ${esc(m.sourceLanguage)}</button>`:''}${!mine&&m.translationUnavailable&&m.sourceLanguage!==$('language').value?'<small>Translation unavailable in mock mode · original shown</small>':''}</div>`}).join('');let rounds=Array.from({length:5},(_,i)=>`<i class="${i<c.roundsUsed?'used':''}">${i+1}</i>`).join('');let body;if(c.revealed){body=`<div class="reveal ${c.result.delta<0?'wrong':''}"><small>THEY WERE</small><div class="who">${c.result.targetType.toUpperCase()}</div><h3>${c.result.delta>0?'+1':c.result.delta<0?'−1':'0'} point</h3><p>You guessed ${c.result.guess.replace('_',' ').toUpperCase()}.</p><button id="keepWalking">KEEP WALKING</button></div>`}else{body=`<div class="msgs">${messages||'<p style="color:#74869d;text-align:center;margin-top:50px;font-size:11px">Start naturally. You have five rounds.</p>'}</div><div class="compose"><input id="msgInput" maxlength="500" placeholder="${roundsLocked?'Five rounds reached — make your guess':'Say something…'}" ${roundsLocked?'disabled':''}><button id="sendMsg" ${roundsLocked?'disabled':''}>Send</button></div>${c.canGuess?'<div class="verdict"><small>YOUR VERDICT</small><div><button data-guess="human">HUMAN</button><button data-guess="ai">AI</button><button data-guess="not_sure">NOT SURE</button></div></div>':isFreeChat?'<div class="verdict"><small>Already judged. Enjoy free chat!</small></div>':'<div class="verdict"><small>Someone is testing you. Reply naturally.</small></div>'}`}
el.innerHTML=`<div class="convHead"><div><b>${esc(c.other.displayName)}</b><small>${isFreeChat?'KNOWN · Free chat':'STRANGER · identity hidden'}</small></div><button id="closeConv">×</button></div>${!c.revealed&&!isFreeChat?`<div class="rounds">${rounds}</div>`:''}${isFreeChat?'<div style="background:#2d426344;color:#85e3d2;font-size:10px;text-align:center;padding:5px">Already judged · Free chat (No points)</div>':''}${body}`;
$('closeConv').onclick=leaveConversation;
if(c.revealed){$('keepWalking').onclick=()=>{conversation=null;renderConversation()};return}
const input=$('msgInput');if(input){$('sendMsg').onclick=()=>sendMessage(input.value);input.onkeydown=e=>{if(e.key==='Enter')sendMessage(input.value)}}
el.querySelectorAll('[data-guess]').forEach(b=>b.onclick=()=>makeGuess(b.dataset.guess));el.querySelectorAll('[data-original]').forEach(b=>b.onclick=()=>{let i=+b.dataset.original,m=c.messages[i],d=el.querySelector(`[data-display="${i}"]`);if(b.textContent.startsWith('Show original')){d.textContent=m.originalText;b.textContent='Show translation'}else{d.textContent=m.displayText||m.translatedText||m.originalText;b.textContent=`Show original · ${m.sourceLanguage}`}})}
async function leaveConversation(){if(conversation&&!conversation.revealed){try{await post('/api/conversation/leave',{uuid,conversationId:conversation.id})}catch{}}conversation=null;renderConversation()}
async function sendMessage(text){if(!text.trim())return;try{const d=await post('/api/conversation/message',{uuid,conversationId:conversation.id,text:text.trim()});conversation=d.conversation;renderConversation()}catch(e){toast(e.message)}}
async function makeGuess(guess){try{const d=await post('/api/conversation/guess',{uuid,conversationId:conversation.id,guess});conversation=d.conversation;player=d.player;$('score').textContent=player.score;renderConversation()}catch(e){toast(e.message)}}
async function showLeaderboard(activeTab='players'){
  try{
    const [pData,mData]=await Promise.all([get('/api/leaderboard'),get('/api/leaderboard/models')]);
    const m=$('leaderboard');m.classList.remove('hidden');
    let rowsHtml='';
    if(activeTab==='players'){
      rowsHtml=`<div class="leaderRow" style="color:#72849c"><span>#</span><span>Player</span><span>Score</span><span>Accuracy</span></div><div class="leaderRows">${pData.rows.map((r,i)=>`<div class="leaderRow"><span>${i+1}</span><span>${esc(r.displayName)}</span><strong>${r.score}</strong><span>${Math.round(r.accuracy*100)}%</span></div>`).join('')||'<p style="text-align:center;color:#6f839e;margin:20px 0">No ranked players yet.</p>'}</div><small>Score first. Decision rate breaks ties.</small>`;
    }else{
      rowsHtml=`<div style="color:#75f2da;font-size:11px;margin-bottom:8px">Which AI is hardest to detect?</div><div class="leaderRow" style="color:#72849c;grid-template-columns:35px 1fr 100px 50px"><span>#</span><span>Model</span><span>Undetected</span><span>Plays</span></div><div class="leaderRows">${mData.rows.map((r,i)=>`<div class="leaderRow" style="grid-template-columns:35px 1fr 100px 50px"><span>${i+1}</span><span><b>${esc(r.model)}</b></span><strong style="color:#75f2da">${r.undetectedRate}%</strong><span>${r.encounters}</span></div>`).join('')||'<p style="text-align:center;color:#6f839e;margin:20px 0">No AI models configured.</p>'}</div><small>Hardest to Detect = (Guessed Human + 0.5 × Not Sure) ÷ Total Plays</small>`;
    }
    m.innerHTML=`<div class="leaderBox"><div class="leaderHead"><div><small>${activeTab==='players'?'GLOBAL':'AI BENCHMARK'}</small><h2>${activeTab==='players'?'Leaderboard':'AI Model Leaderboard'}</h2></div><button id="closeLb">×</button></div><div style="display:flex;gap:6px;margin-bottom:12px"><button id="tabPlayers" style="flex:1;padding:6px;border-radius:8px;border:1px solid #75f2da44;background:${activeTab==='players'?'#75f2da22':'transparent'};color:${activeTab==='players'?'#75f2da':'#8fa2b8'};cursor:pointer">🏆 Players</button><button id="tabModels" style="flex:1;padding:6px;border-radius:8px;border:1px solid #75f2da44;background:${activeTab==='models'?'#75f2da22':'transparent'};color:${activeTab==='models'?'#75f2da':'#8fa2b8'};cursor:pointer">🤖 AI Models</button></div>${rowsHtml}</div>`;
    $('closeLb').onclick=()=>m.classList.add('hidden');
    $('tabPlayers').onclick=()=>showLeaderboard('players');
    $('tabModels').onclick=()=>showLeaderboard('models');
  }catch(e){toast(e.message)}
}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}

if(new URLSearchParams(location.search).get('demo')==='1') setTimeout(()=>$('enter').click(),120);
